version: "3"
services:
  api:
    container_name: "fastapi"
    image: api
#    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@127.0.0.1:5432/postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#    depends_on:
#      - db
#    networks:
#      - custom
#    volumes:
#      - .:/api
#  db:
#    container_name: "postgres"
#    image: postgres:15.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - custom
#    volumes:
#      - postgres-db:/var/lib/postgresql/data
#  db_test:
#    container_name: "postgres_test"
#    image: postgres:15.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres_test
#      - POSTGRES_PASSWORD=postgres_test
#      - POSTGRES_DB=postgres_test
#    ports:
#      - "5433:5432"
#    networks:
#      - custom
#    volumes:
#      - postgres-db:/var/lib/postgresql/data
#networks:
#  custom:
#    driver: bridge
#volumes:
#  postgres-db: