version: "3.8"

services:
  api_test:
    container_name: "api_test"
    image: api_test
    environment:
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db:5433/postgres
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db_test
    command: "pytest"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom
    volumes:
      - postgres-db:/var/lib/postgresql/data

networks:
  custom:
    name: network_test
    driver: bridge
volumes:
  postgres-db:

