version: "3.8"

services:
  api:
    container_name: "api"
    image: api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
#    command: "pytest"
    networks:
      - custom
  db:
    container_name: "db"
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    networks:
      - custom
    volumes:
      - postgres-db:/var/lib/postgresql/data
  db_test:
    container_name: "db_test"
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - custom
    volumes:
      - postgres-db:/var/lib/postgresql/data

networks:
  custom:
    name: network_api_db
    driver: bridge
volumes:
  postgres-db: