version: "3.8"

services:
  api:
    container_name: "api"
    image: api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "python3 main.py"
    networks:
      - custom
  db:
    container_name: "db"
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - postgres-db:/var/lib/postgresql/data

networks:
  custom:
    name: network_api_db
    driver: bridge
volumes:
  postgres-db: