version: "3.8"

services:
  test:
    container_name: "test"
    image: test
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db_test:5432/postgres
    depends_on:
      db_test:
        condition: service_healthy
    command: "pytest"
    networks:
      - net_test
  db_test:
    container_name: "db_test"
    image: postgres:15.1-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - net_test

networks:
  net_test:
    driver: bridge